apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: myapp
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: kubernetes
        image: mylandmarktech/spring-boot-mongo:latest
        ports:
        - containerPort: 8080
