apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels: 
    app: demo
  name: demo-service
spec:
  selector:
    app: demo
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  Type: NodePort
status: 
  loadBalancer: {}
